### ISSUE TITLE
rp-request_uri-enc: Improve error logging when resolving the Request URI fails

### ISSUE THREAD

**Issue by zandbelt** [openid-certification/oidctest#10]
Running `rp-request_uri-enc` on the latest code results in an error:

````
[04/May/2017:06:38:12]  
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/CherryPy-8.9.1-py3.5.egg/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python3.5/dist-packages/CherryPy-8.9.1-py3.5.egg/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/CherryPy-8.9.1-py3.5.egg/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.5/dist-packages/oidctest-0.7.0-py3.5.egg/oidctest/cp/op.py", line 200, in index
    resp = op.authorization_endpoint(kwargs)
  File "/usr/local/lib/python3.5/dist-packages/oidctest-0.7.0-py3.5.egg/oidctest/rp/provider.py", line 418, in authorization_endpoint
    **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/oic-0.10.0.0-py3.5.egg/oic/oic/provider.py", line 735, in authorization_endpoint
    info = self.auth_init(request, request_class=AuthorizationRequest)
  File "/usr/local/lib/python3.5/dist-packages/oic-0.10.0.0-py3.5.egg/oic/oauth2/provider.py", line 401, in auth_init
    areq = self.filter_request(areq)
  File "/usr/local/lib/python3.5/dist-packages/oic-0.10.0.0-py3.5.egg/oic/oic/provider.py", line 688, in filter_request
    before = req.to_dict()
AttributeError: 'Response' object has no attribute 'to_dict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/CherryPy-8.9.1-py3.5.egg/cherrypy/_cprequest.py", line 589, in run
    self.respond(pi)
  File "/usr/local/lib/python3.5/dist-packages/CherryPy-8.9.1-py3.5.egg/cherrypy/_cprequest.py", line 690, in respond
    self.handle_error()
  File "/usr/local/lib/python3.5/dist-packages/CherryPy-8.9.1-py3.5.egg/cherrypy/_cprequest.py", line 767, in handle_error
    self.error_response()
  File "/usr/local/lib/python3.5/dist-packages/oidctest-0.7.0-py3.5.egg/oidctest/cp/op.py", line 30, in handle_error
    "<html><body>Sorry, an error occured</body></html>"
  File "/usr/local/lib/python3.5/dist-packages/CherryPy-8.9.1-py3.5.egg/cherrypy/__init__.py", line 239, in __setattr__
    setattr(child, name, value)
  File "/usr/local/lib/python3.5/dist-packages/CherryPy-8.9.1-py3.5.egg/cherrypy/_cprequest.py", line 831, in __set__
    raise ValueError(self.unicode_err)
ValueError: Page handlers MUST return bytes. Use tools.encode if you wish to return unicode.
````

**Comment by zandbelt** [comment]
Actually the problem was on my side: the request URI could not correctly been resolved. I'm turning this into an enhancement request since it would be highly convenient to improve error logging around this. (it used to be better as I recall, where I could actually see resolving the request URI failing with a proper error message)

**Comment by selfissued** [comment]
Hans said that the issue is to improve the error logging for this case

**Comment by zandbelt** [comment]
this was deployed just now as part of OP 2.2.1 https://github.com/openid-certification/oidctest/releases/tag/v1.2.0
