### ISSUE TITLE
incidental 500 on Discovery

### ISSUE THREAD

**Issue by zandbelt** [openid-certification/oidctest#12]
Sometimes the RP test suite is stalled and only returns HTTP 500 on Discovery document requests, e.g.:
````
Message: '86.110.65.8 - - [09/May/2017:08:21:45] "GET /mod_auth_openidc/rp-nonce-unless-code-flow/.well-known/openid-configuration HTTP/1.1" 500 1967 "" "mod_auth_openidc"'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.5/logging/__init__.py", line 983, in emit
    stream.write(self.terminator)
OSError: [Errno 5] Input/output error
Call stack:
  File "/usr/lib/python3.5/threading.py", line 882, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/oictest/.local/lib/python3.5/site-packages/cherrypy/wsgiserver/__init__.py", line 1594, in run
    conn.communicate()
  File "/home/oictest/.local/lib/python3.5/site-packages/cherrypy/wsgiserver/__init__.py", line 1408, in communicate
    req.respond()
  File "/home/oictest/.local/lib/python3.5/site-packages/cherrypy/wsgiserver/__init__.py", line 862, in respond
    self.server.gateway(self).respond()
  File "/home/oictest/.local/lib/python3.5/site-packages/cherrypy/wsgiserver/__init__.py", line 2335, in respond
    response = self.req.server.wsgi_app(self.env, self.start_response)
  File "/home/oictest/.local/lib/python3.5/site-packages/cherrypy/_cptree.py", line 287, in __call__
    return app(environ, start_response)
  File "/home/oictest/.local/lib/python3.5/site-packages/cherrypy/_cptree.py", line 153, in __call__
    return self.wsgiapp(environ, start_response)
  File "/home/oictest/.local/lib/python3.5/site-packages/cherrypy/_cpwsgi.py", line 450, in __call__
    return head(environ, start_response)
````
This requires a restart to make things operational again.

**Comment by zandbelt** [comment]
Another type of error seems to occur as well:
````
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/CherryPy-8.9.1-py3.5.egg/cherrypy/_cprequest.py", line 642, in respond
    self.get_resource(path_info)
  File "/usr/local/lib/python3.5/dist-packages/CherryPy-8.9.1-py3.5.egg/cherrypy/_cprequest.py", line 760, in get_resource
    dispatch(path)
  File "/usr/local/lib/python3.5/dist-packages/CherryPy-8.9.1-py3.5.egg/cherrypy/_cpdispatch.py", line 294, in __call__
    func, vpath = self.find_handler(path_info)
  File "/usr/local/lib/python3.5/dist-packages/CherryPy-8.9.1-py3.5.egg/cherrypy/_cpdispatch.py", line 357, in find_handler
    subnode = dispatch(vpath=iternames)
  File "/usr/local/lib/python3.5/dist-packages/oidctest-0.7.0-py3.5.egg/oidctest/cp/op.py", line 407, in _cp_dispatch
    endpoint)[0]
  File "/usr/local/lib/python3.5/dist-packages/oidctest-0.7.0-py3.5.egg/oidctest/cp/op_handler.py", line 64, in get
    write_jwks_uri(_op, self.op_args)
  File "/usr/local/lib/python3.5/dist-packages/oidctest-0.7.0-py3.5.egg/oidctest/cp/op_handler.py", line 16, in write_jwks_uri
    with open(filename, "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: './static/jwks_W9GJlKzJsFjt1ku2.json'
````

**Comment by rohe** [comment]
That one I understand and have a place to start working on a fix from. The first log excerpt (and this is not Hans's fault) gives no clue as to what's really amiss.

**Comment by zandbelt** [comment]
it seems to be fixed in the current code base
