### ISSUE TITLE
OP-OAuth-2nd-Revokes not handling invalid responses, showing traceback

### ISSUE THREAD

**Issue by TomDemeranville** [openid-certification/oidctest#133]
I'm seeing an error when I run OP-OAuth-2nd-Revokes.   My code is returning a HTTP 400 and this body:

`{"error":"invalid_grant","error_description":"Reused` authorization code: Okgm6i"}`

It's set up for the code flow at https://op.certification.openid.net:61514/ You can recreate if you like - our OAuth flow allows you to register a new account.

> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/dist-packages/otest-0.7.2-py3.6.egg/otest/aus/tool.py", line 87, in run_flow
>     resp = _oper()
>   File "/usr/local/lib/python3.6/dist-packages/otest-0.7.2-py3.6.egg/otest/operation.py", line 105, in __call__
>     res = self.run(*args, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/oidctest-0.7.3-py3.6.egg/oidctest/op/oper.py", line 316, in run
>     **args)
>   File "/usr/local/lib/python3.6/dist-packages/otest-0.7.2-py3.6.egg/otest/operation.py", line 200, in catch_exception_and_error
>     if res['error'] not in self.expect_error['error']:
>   File "/usr/local/lib/python3.6/dist-packages/oic-0.14.0-py3.6.egg/oic/oauth2/message.py", line 773, in __getitem__
>     return self._dict[item]
> KeyError: 'error'
>

**Comment by selfissued** [comment]
"error-description" should be "error_description".  Is that a bug in your code?

We agree that the test suite should handle this situation more gracefully.
