### ISSUE TITLE
improve error message when id_token is missing in token response

### ISSUE THREAD

**Issue by zandbelt** [openid-certification/oidctest#141]
As reported on the certification list:

> I was trying out my OIDC server with the op.certification.openid.net testing service, and got the following page for this kind of callback URL:

```
https://op.certification.openid.net:61563/authz_cb?code=a5eb95d8-952a-41f6-bf60-2f5d9ae891ae&state=v0loSwLe9IuHuKVw

********************************************************************************
Something went seriously wrong, please tell us at certification@oidf.org
********************************************************************************


Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/otest-0.7.2-py3.6.egg/otest/aus/tool.py", line 87, in run_flow
    resp = _oper()
  File "/usr/local/lib/python3.6/dist-packages/otest-0.7.2-py3.6.egg/otest/operation.py", line 105, in __call__
    res = self.run(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/oidctest-0.7.3-py3.6.egg/oidctest/op/oper.py", line 205, in run
    res = self._run()
  File "/usr/local/lib/python3.6/dist-packages/oidctest-0.7.3-py3.6.egg/oidctest/op/oper.py", line 239, in _run
    if not same_issuer(self.conv.info["issuer"], atr["id_token"]["iss"]):
  File "/usr/local/lib/python3.6/dist-packages/oic-0.14.0-py3.6.egg/oic/oauth2/message.py", line 773, in __getitem__
    return self._dict[item]
KeyError: 'id_token'
```

> This issue is most likely caused by the missing id_token as my server doesn't return it yet, but I thought I'd e-mail you as requested by the error page. :-)

**Comment by zandbelt** [comment]
By the same token, a signature verification error returns:
```
********************************************************************************
Something went seriously wrong, please tell us at certification@oidf.org
********************************************************************************


Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/otest-0.7.2-py3.6.egg/otest/aus/tool.py", line 87, in run_flow
    resp = _oper()
  File "/usr/local/lib/python3.6/dist-packages/otest-0.7.2-py3.6.egg/otest/operation.py", line 105, in __call__
    res = self.run(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/oidctest-0.7.3-py3.6.egg/oidctest/op/oper.py", line 205, in run
    res = self._run()
  File "/usr/local/lib/python3.6/dist-packages/oidctest-0.7.3-py3.6.egg/oidctest/op/oper.py", line 220, in _run
    request_args=self.req_args, **self.op_args)
  File "/usr/local/lib/python3.6/dist-packages/otest-0.7.2-py3.6.egg/otest/operation.py", line 171, in catch_exception_and_error
    res = func(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/oic-0.14.0-py3.6.egg/oic/oic/__init__.py", line 681, in do_access_token_request
    authn_method, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/oic-0.14.0-py3.6.egg/oic/oauth2/__init__.py", line 758, in do_access_token_request
    http_args=http_args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/oic-0.14.0-py3.6.egg/oic/oauth2/__init__.py", line 681, in request_and_return
    **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/oic-0.14.0-py3.6.egg/oic/oauth2/__init__.py", line 635, in parse_request_response
    state, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/oic-0.14.0-py3.6.egg/oic/oauth2/__init__.py", line 562, in parse_response
    verf = resp.verify(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/oic-0.14.0-py3.6.egg/oic/oic/message.py", line 302, in verify
    idt = IdToken().from_jwt(str(self["id_token"]), **args)
  File "/usr/local/lib/python3.6/dist-packages/oic-0.14.0-py3.6.egg/oic/oauth2/message.py", line 679, in from_jwt
    _jw.verify_compact(txt, key)
  File "/usr/local/lib/python3.6/dist-packages/pyjwkest-1.4.0-py3.6.egg/jwkest/jws.py", line 517, in verify_compact
    return self.verify_compact_verbose(jws, keys, allow_none, sigalg)['msg']
  File "/usr/local/lib/python3.6/dist-packages/pyjwkest-1.4.0-py3.6.egg/jwkest/jws.py", line 588, in verify_compact_verbose
    raise BadSignature()
jwkest.BadSignature
```
which also leaves room for improvement.

**Comment by zandbelt** [comment]
and in the same boat, when the `iss` value in the `id_token` is not matching the configured issuer we get:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/oic-0.14.0-py3.6.egg/oic/oauth2/message.py", line 679, in from_jwt
    _jw.verify_compact(txt, key)
  File "/usr/local/lib/python3.6/dist-packages/pyjwkest-1.4.0-py3.6.egg/jwkest/jws.py", line 517, in verify_compact
    return self.verify_compact_verbose(jws, keys, allow_none, sigalg)['msg']
  File "/usr/local/lib/python3.6/dist-packages/pyjwkest-1.4.0-py3.6.egg/jwkest/jws.py", line 565, in verify_compact_verbose
    "No key with kid: %s" % (self["kid"]))
jwkest.jws.NoSuitableSigningKeys: No key with kid: aa436c3f63b281ce0d976da0b51a34860ff960eb
```
that could/should be improved along the same lines
