### ISSUE TITLE
/oidc/certs inaccessible from test suite

### ISSUE THREAD

**Issue by rdfield** [openid-certification/oidctest#148]
Fetching the certs directly from a browser works OK, but from the test suite server an error is seen:

[1]
019-03-06 14:09:21,553 oic.oauth2:DEBUG Initial response parsing => "{'code': '<REDACTED>', 'id_token': 'eyJraWQiOiJyc2EyNTYiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJub25jZSI6IjVjZ1A2MTZlcVFENm92bHciLCJhdWQiOiJkUmxPZ0Y1Z015c0R5RU1EIiwiaWF0IjoxNTUxODgxMjI1LCJzdWIiOiI5NjRmYjViZS00MGYzLTRkZTYtYmJkOC1kM2NiZGRlMGZiMDIiLCJpc3MiOiJodHRwczovL21jeGRldi5tdmluZS5jb20vaWRwL29pZGMiLCJjX2hhc2giOiJqd3dJMVlDNHZiUFl0eFRlVVBWT0F3IiwiZXhwIjoxNTUxODgxMjQyLCJhdXRoX3RpbWUiOjE1NTE4ODEyMjV9.CHnveGXJ_-oErZAasZY6ivCnhBFlffZvHJCP6FD9KlYZkDLlbDEPpiRdxhgIxcR-jgSILtuKYJDK3A9RR831qWNEs_AepQqfXcT3OOpxUpOUmjrunrc7j-YrJUktxbOF24t3YgnOeIudOipReT_QuOQLkpR_8CKfGZXiRIWg0HakSh0b1pggUjIFHZUzI5sRmvqEldiSDz6cPfgOOhDqbpzAEeGLiF7uKqdkUF9CcF9HIApwBf8th4VCQnbyIItw10RZyLPnTILuptLWsdm-VnU9X9EgQZs_jQweDue_opy3vrSLJuXt4aWk9ArRaVcPSJSUCEh_gXw4m84-p4XVyA', 'state': 'Xy4697ArXxteyZ5c'}"
2019-03-06 14:09:21,553 oic.oauth2:DEBUG Verify response with {'keyjar': <KeyJar(issuers=['', 'https://mcxdev.mvine.com/idp/oidc'])>, 'client_id': 'dRlOgF5gMysDyEMD', 'iss': 'https://mcxdev.mvine.com/idp/oidc'}
2019-03-06 14:09:21,553 oic.oauth2.message:DEBUG Raw JSON: {'nonce': '5cgP616eqQD6ovlw', 'aud': 'dRlOgF5gMysDyEMD', 'iat': 1551881225, 'sub': '964fb5be-40f3-4de6-bbd8-d3cbdde0fb02', 'iss': 'https://mcxdev.mvine.com/idp/oidc', 'c_hash': 'jwwI1YC4vbPYtxTeUPVOAw', 'exp': 1551881242, 'auth_time': 1551881225}
2019-03-06 14:09:21,553 oic.oauth2.message:DEBUG JWS header: {'kid': 'rsa256', 'typ': 'JWT', 'alg': 'RS256'}
2019-03-06 14:09:21,554 root:DEBUG KeyBundle fetch keys from: https://mcxdev.mvine.com/idp/oidc/certs
2019-03-06 14:09:21,554 urllib3.connectionpool:DEBUG Starting new HTTPS connection (1): mcxdev.mvine.com

2019-03-06 14:09:26,738 oic.utils.keyio:ERROR HTTPSConnectionPool(host='mcxdev.mvine.com', port=443): Read timed out. (read timeout=5)
2019-03-06 14:09:26,738 otest.handling:ERROR [run_sequence] ExcList: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 852, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib/python3.6/ssl.py", line 817, in __init__
    self.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:830: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 349, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='mcxdev.mvine.com', port=443): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/oic-0.15.1-py3.6.egg/oic/utils/keyio.py", line 182, in do_remote
    r = requests.get(self.source, **args)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 520, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 630, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='mcxdev.mvine.com', port=443): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/otest-0.7.3-py3.6.egg/otest/aus/request.py", line 331, in parse_response
    keyjar=_conv.entity.keyjar  # , algs=algs
  File "/usr/local/lib/python3.6/dist-packages/oic-0.15.1-py3.6.egg/oic/oauth2/__init__.py", line 542, in parse_response
    verf = resp.verify(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/oic-0.15.1-py3.6.egg/oic/oic/message.py", line 371, in verify
    self["id_token"] = verify_id_token(self, check_hash=True, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/oic-0.15.1-py3.6.egg/oic/oic/message.py", line 296, in verify_id_token
    idt = IdToken().from_jwt(_jws, **args)
  File "/usr/local/lib/python3.6/dist-packages/oic-0.15.1-py3.6.egg/oic/oauth2/message.py", line 662, in from_jwt
    _jw, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/oic-0.15.1-py3.6.egg/oic/oauth2/message.py", line 556, in get_verify_keys
    _key = keyjar.get_key_by_kid(_kid, _iss)
  File "/usr/local/lib/python3.6/dist-packages/oic-0.15.1-py3.6.egg/oic/utils/keyio.py", line 616, in get_key_by_kid
    _key = kb.get_key_with_kid(kid)
  File "/usr/local/lib/python3.6/dist-packages/oic-0.15.1-py3.6.egg/oic/utils/keyio.py", line 342, in get_key_with_kid
    self.update()
  File "/usr/local/lib/python3.6/dist-packages/oic-0.15.1-py3.6.egg/oic/utils/keyio.py", line 273, in update
    res = self.do_remote()
  File "/usr/local/lib/python3.6/dist-packages/oic-0.15.1-py3.6.egg/oic/utils/keyio.py", line 186, in do_remote
    REMOTE_FAILED.format(self.source, str(err)))
  File "/usr/local/lib/python3.6/dist-packages/oic-0.15.1-py3.6.egg/oic/utils/keyio.py", line 40, in raise_exception
    raise excep(_err, 'application/json')
oic.utils.keyio.UpdateFailed: {"error": "service_error", "error_description": "Remote key update from 'https://mcxdev.mvine.com/idp/oidc/certs' failed, HTTP status HTTPSConnectionPool(host='mcxdev.mvine.com', port=443): Read timed out. (read timeout=5)"}

2019-03-06 14:09:26,738 otest.handling:ERROR [run_sequence] Exception: {"error": "service_error", "error_description": "Remote key update from 'https://mcxdev.mvine.com/idp/oidc/certs' failed, HTTP status HTTPSConnectionPool(host='mcxdev.mvine.com', port=443): Read timed out. (read timeout=5)"}

**Comment by zandbelt** [comment]
a bit strange but I suspect it is due to an SSL certification verification issue, see below, where it started out to be that but then recently turned into a connection error; I'd still fix the cert chain and see what happens next, see also https://www.ssllabs.com/ssltest/analyze.html?d=mcxdev.mvine.com where it mentions that the cert chain is incomplete

```
cat op_test.log | grep -A 2 "fetch keys from: https://mcxdev.mvine.com/idp/oidc/certs"
2019-03-06 11:43:14,203 root:DEBUG KeyBundle fetch keys from: https://mcxdev.mvine.com/idp/oidc/certs
2019-03-06 11:43:14,205 urllib3.connectionpool:DEBUG Starting new HTTPS connection (1): mcxdev.mvine.com
2019-03-06 11:43:14,548 oic.utils.keyio:ERROR HTTPSConnectionPool(host='mcxdev.mvine.com', port=443): Max retries exceeded with url: /idp/oidc/certs (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)'),))
--
2019-03-06 11:43:25,480 root:DEBUG KeyBundle fetch keys from: https://mcxdev.mvine.com/idp/oidc/certs
2019-03-06 11:43:25,481 urllib3.connectionpool:DEBUG Starting new HTTPS connection (1): mcxdev.mvine.com
2019-03-06 11:43:25,660 oic.utils.keyio:ERROR HTTPSConnectionPool(host='mcxdev.mvine.com', port=443): Max retries exceeded with url: /idp/oidc/certs (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)'),))
--
2019-03-06 11:43:34,125 root:DEBUG KeyBundle fetch keys from: https://mcxdev.mvine.com/idp/oidc/certs
2019-03-06 11:43:34,126 urllib3.connectionpool:DEBUG Starting new HTTPS connection (1): mcxdev.mvine.com
2019-03-06 11:43:34,303 oic.utils.keyio:ERROR HTTPSConnectionPool(host='mcxdev.mvine.com', port=443): Max retries exceeded with url: /idp/oidc/certs (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)'),))
--
2019-03-06 11:43:42,018 root:DEBUG KeyBundle fetch keys from: https://mcxdev.mvine.com/idp/oidc/certs
2019-03-06 11:43:42,019 urllib3.connectionpool:DEBUG Starting new HTTPS connection (1): mcxdev.mvine.com
2019-03-06 11:43:42,197 oic.utils.keyio:ERROR HTTPSConnectionPool(host='mcxdev.mvine.com', port=443): Max retries exceeded with url: /idp/oidc/certs (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)'),))
--
2019-03-06 11:43:46,678 root:DEBUG KeyBundle fetch keys from: https://mcxdev.mvine.com/idp/oidc/certs
2019-03-06 11:43:46,679 urllib3.connectionpool:DEBUG Starting new HTTPS connection (1): mcxdev.mvine.com
2019-03-06 11:43:46,858 oic.utils.keyio:ERROR HTTPSConnectionPool(host='mcxdev.mvine.com', port=443): Max retries exceeded with url: /idp/oidc/certs (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)'),))
--
2019-03-06 11:44:23,206 root:DEBUG KeyBundle fetch keys from: https://mcxdev.mvine.com/idp/oidc/certs
2019-03-06 11:44:23,207 urllib3.connectionpool:DEBUG Starting new HTTPS connection (1): mcxdev.mvine.com
2019-03-06 11:44:23,430 oic.utils.keyio:ERROR HTTPSConnectionPool(host='mcxdev.mvine.com', port=443): Max retries exceeded with url: /idp/oidc/certs (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)'),))
--
2019-03-06 11:44:34,355 root:DEBUG KeyBundle fetch keys from: https://mcxdev.mvine.com/idp/oidc/certs
2019-03-06 11:44:34,356 urllib3.connectionpool:DEBUG Starting new HTTPS connection (1): mcxdev.mvine.com
2019-03-06 11:44:34,534 oic.utils.keyio:ERROR HTTPSConnectionPool(host='mcxdev.mvine.com', port=443): Max retries exceeded with url: /idp/oidc/certs (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)'),))
--
2019-03-06 11:44:48,269 root:DEBUG KeyBundle fetch keys from: https://mcxdev.mvine.com/idp/oidc/certs
2019-03-06 11:44:48,270 urllib3.connectionpool:DEBUG Starting new HTTPS connection (1): mcxdev.mvine.com
2019-03-06 11:44:48,448 oic.utils.keyio:ERROR HTTPSConnectionPool(host='mcxdev.mvine.com', port=443): Max retries exceeded with url: /idp/oidc/certs (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)'),))
--
2019-03-06 11:45:08,829 root:DEBUG KeyBundle fetch keys from: https://mcxdev.mvine.com/idp/oidc/certs
2019-03-06 11:45:08,829 urllib3.connectionpool:DEBUG Starting new HTTPS connection (1): mcxdev.mvine.com
2019-03-06 11:45:09,008 oic.utils.keyio:ERROR HTTPSConnectionPool(host='mcxdev.mvine.com', port=443): Max retries exceeded with url: /idp/oidc/certs (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)'),))
--
2019-03-06 11:45:36,471 root:DEBUG KeyBundle fetch keys from: https://mcxdev.mvine.com/idp/oidc/certs
2019-03-06 11:45:36,472 urllib3.connectionpool:DEBUG Starting new HTTPS connection (1): mcxdev.mvine.com
2019-03-06 11:45:36,761 oic.utils.keyio:ERROR HTTPSConnectionPool(host='mcxdev.mvine.com', port=443): Max retries exceeded with url: /idp/oidc/certs (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)'),))
--
2019-03-06 11:46:09,967 root:DEBUG KeyBundle fetch keys from: https://mcxdev.mvine.com/idp/oidc/certs
2019-03-06 11:46:09,968 urllib3.connectionpool:DEBUG Starting new HTTPS connection (1): mcxdev.mvine.com
2019-03-06 11:46:10,147 oic.utils.keyio:ERROR HTTPSConnectionPool(host='mcxdev.mvine.com', port=443): Max retries exceeded with url: /idp/oidc/certs (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)'),))
--
2019-03-06 11:46:35,141 root:DEBUG KeyBundle fetch keys from: https://mcxdev.mvine.com/idp/oidc/certs
2019-03-06 11:46:35,143 urllib3.connectionpool:DEBUG Starting new HTTPS connection (1): mcxdev.mvine.com
2019-03-06 11:46:35,322 oic.utils.keyio:ERROR HTTPSConnectionPool(host='mcxdev.mvine.com', port=443): Max retries exceeded with url: /idp/oidc/certs (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)'),))
--
2019-03-06 11:46:44,110 root:DEBUG KeyBundle fetch keys from: https://mcxdev.mvine.com/idp/oidc/certs
2019-03-06 11:46:44,111 urllib3.connectionpool:DEBUG Starting new HTTPS connection (1): mcxdev.mvine.com
2019-03-06 11:46:44,425 oic.utils.keyio:ERROR HTTPSConnectionPool(host='mcxdev.mvine.com', port=443): Max retries exceeded with url: /idp/oidc/certs (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)'),))
--
2019-03-06 11:49:42,468 root:DEBUG KeyBundle fetch keys from: https://mcxdev.mvine.com/idp/oidc/certs
2019-03-06 11:49:42,470 urllib3.connectionpool:DEBUG Starting new HTTPS connection (1): mcxdev.mvine.com
2019-03-06 11:49:42,792 oic.utils.keyio:ERROR HTTPSConnectionPool(host='mcxdev.mvine.com', port=443): Max retries exceeded with url: /idp/oidc/certs (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)'),))
--
2019-03-06 11:51:01,376 root:DEBUG KeyBundle fetch keys from: https://mcxdev.mvine.com/idp/oidc/certs
2019-03-06 11:51:01,377 urllib3.connectionpool:DEBUG Starting new HTTPS connection (1): mcxdev.mvine.com
2019-03-06 11:51:01,725 oic.utils.keyio:ERROR HTTPSConnectionPool(host='mcxdev.mvine.com', port=443): Max retries exceeded with url: /idp/oidc/certs (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)'),))
--
2019-03-06 11:58:42,014 root:DEBUG KeyBundle fetch keys from: https://mcxdev.mvine.com/idp/oidc/certs
2019-03-06 11:58:42,017 urllib3.connectionpool:DEBUG Starting new HTTPS connection (1): mcxdev.mvine.com
2019-03-06 11:58:42,197 oic.utils.keyio:ERROR HTTPSConnectionPool(host='mcxdev.mvine.com', port=443): Max retries exceeded with url: /idp/oidc/certs (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)'),))
--
2019-03-06 11:59:49,770 root:DEBUG KeyBundle fetch keys from: https://mcxdev.mvine.com/idp/oidc/certs
2019-03-06 11:59:49,771 urllib3.connectionpool:DEBUG Starting new HTTPS connection (1): mcxdev.mvine.com
2019-03-06 11:59:50,042 oic.utils.keyio:ERROR HTTPSConnectionPool(host='mcxdev.mvine.com', port=443): Max retries exceeded with url: /idp/oidc/certs (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)'),))
--
2019-03-06 13:17:40,858 root:DEBUG KeyBundle fetch keys from: https://mcxdev.mvine.com/idp/oidc/certs
2019-03-06 13:17:40,859 urllib3.connectionpool:DEBUG Starting new HTTPS connection (1): mcxdev.mvine.com
2019-03-06 13:17:41,134 oic.utils.keyio:ERROR HTTPSConnectionPool(host='mcxdev.mvine.com', port=443): Max retries exceeded with url: /idp/oidc/certs (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)'),))
--
2019-03-06 13:19:16,788 root:DEBUG KeyBundle fetch keys from: https://mcxdev.mvine.com/idp/oidc/certs
2019-03-06 13:19:16,789 urllib3.connectionpool:DEBUG Starting new HTTPS connection (1): mcxdev.mvine.com
2019-03-06 13:19:17,012 oic.utils.keyio:ERROR HTTPSConnectionPool(host='mcxdev.mvine.com', port=443): Max retries exceeded with url: /idp/oidc/certs (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)'),))
--
2019-03-06 14:07:09,161 root:DEBUG KeyBundle fetch keys from: https://mcxdev.mvine.com/idp/oidc/certs
2019-03-06 14:07:09,162 urllib3.connectionpool:DEBUG Starting new HTTPS connection (1): mcxdev.mvine.com
2019-03-06 14:07:14,372 oic.utils.keyio:ERROR HTTPSConnectionPool(host='mcxdev.mvine.com', port=443): Read timed out. (read timeout=5)
--
2019-03-06 14:09:21,554 root:DEBUG KeyBundle fetch keys from: https://mcxdev.mvine.com/idp/oidc/certs
2019-03-06 14:09:21,554 urllib3.connectionpool:DEBUG Starting new HTTPS connection (1): mcxdev.mvine.com
2019-03-06 14:09:26,738 oic.utils.keyio:ERROR HTTPSConnectionPool(host='mcxdev.mvine.com', port=443): Read timed out. (read timeout=5)

```

**Comment by rdfield** [comment]
Works OK with complete cert chain.

**Comment by bitman694** [comment]
@zandbelt I met a similar problem. Our implement have passed OP-implict and now I'm testing OP-code. And something may be wrong.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.6/ssl.py", line 1012, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.6/ssl.py", line 874, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='test.is.ac.cn', port=443): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/oic-0.15.1-py3.6.egg/oic/utils/keyio.py", line 182, in do_remote
    r = requests.get(self.source, **args)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 520, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 630, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='test.is.ac.cn', port=443): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/otest-0.7.3-py3.6.egg/otest/aus/tool.py", line 87, in run_flow
    resp = _oper()
  File "/usr/local/lib/python3.6/dist-packages/otest-0.7.3-py3.6.egg/otest/operation.py", line 105, in __call__
    res = self.run(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/oidctest-0.7.5-py3.6.egg/oidctest/op/oper.py", line 216, in run
    res = self._run()
  File "/usr/local/lib/python3.6/dist-packages/oidctest-0.7.5-py3.6.egg/oidctest/op/oper.py", line 244, in _run
    request_args=self.req_args, **self.op_args)
  File "/usr/local/lib/python3.6/dist-packages/otest-0.7.3-py3.6.egg/otest/operation.py", line 171, in catch_exception_and_error
    res = func(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/oic-0.15.1-py3.6.egg/oic/oic/__init__.py", line 674, in do_access_token_request
    authn_method, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/oic-0.15.1-py3.6.egg/oic/oauth2/__init__.py", line 738, in do_access_token_request
    http_args=http_args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/oic-0.15.1-py3.6.egg/oic/oauth2/__init__.py", line 661, in request_and_return
    **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/oic-0.15.1-py3.6.egg/oic/oauth2/__init__.py", line 615, in parse_request_response
    state, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/oic-0.15.1-py3.6.egg/oic/oauth2/__init__.py", line 542, in parse_response
    verf = resp.verify(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/oic-0.15.1-py3.6.egg/oic/oic/message.py", line 339, in verify
    self["id_token"] = verify_id_token(self, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/oic-0.15.1-py3.6.egg/oic/oic/message.py", line 296, in verify_id_token
    idt = IdToken().from_jwt(_jws, **args)
  File "/usr/local/lib/python3.6/dist-packages/oic-0.15.1-py3.6.egg/oic/oauth2/message.py", line 662, in from_jwt
    _jw, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/oic-0.15.1-py3.6.egg/oic/oauth2/message.py", line 556, in get_verify_keys
    _key = keyjar.get_key_by_kid(_kid, _iss)
  File "/usr/local/lib/python3.6/dist-packages/oic-0.15.1-py3.6.egg/oic/utils/keyio.py", line 616, in get_key_by_kid
    _key = kb.get_key_with_kid(kid)
  File "/usr/local/lib/python3.6/dist-packages/oic-0.15.1-py3.6.egg/oic/utils/keyio.py", line 342, in get_key_with_kid
    self.update()
  File "/usr/local/lib/python3.6/dist-packages/oic-0.15.1-py3.6.egg/oic/utils/keyio.py", line 273, in update
    res = self.do_remote()
  File "/usr/local/lib/python3.6/dist-packages/oic-0.15.1-py3.6.egg/oic/utils/keyio.py", line 186, in do_remote
    REMOTE_FAILED.format(self.source, str(err)))
  File "/usr/local/lib/python3.6/dist-packages/oic-0.15.1-py3.6.egg/oic/utils/keyio.py", line 40, in raise_exception
    raise excep(_err, 'application/json')
oic.utils.keyio.UpdateFailed: {"error": "service_error", "error_description": "Remote key update from 'https://test.is.ac.cn/jwks' failed, HTTP status HTTPSConnectionPool(host='test.is.ac.cn', port=443): Read timed out. (read timeout=5)"}
