### ISSUE TITLE
OP-FrontChannel-RpInitLogout-all

### ISSUE THREAD

**Issue by panva** [openid-certification/oidctest#161]
ERROR state, with the following in the error log

https://new-op.certification.openid.net:60011/test_info/OP-FrontChannel-RpInitLogout-all

```
['Traceback (most recent call last):\n', ' File "/usr/local/lib/python3.6/dist-packages/oidctest-0.8.1-py3.6.egg/oidctest/optt/__init__.py", line 317, in _endpoint\n resp = self.tester.handle_request(request, **kwargs)\n', "TypeError: handle_request() got an unexpected keyword argument 'entity_id'\n"]
```

Same for `OP-FrontChannel-RpInitLogout-only-state`

**Comment by rohe** [comment]
Checked in a fix for this.

**Comment by panva** [comment]
@rohe 
```
['Traceback (most recent call last):\n', ' File "/usr/local/lib/python3.6/dist-packages/oidctest-0.8.1-py3.6.egg/oidctest/optt/__init__.py", line 317, in _endpoint\n resp = self.tester.handle_request(request, **kwargs)\n', "TypeError: handle_request() got an unexpected keyword argument 'sid'\n"]
```

**Comment by rohe** [comment]
Checked in fixes for this. One specific in oidctest and one more generic in otest.

**Comment by zandbelt** [comment]
rolled out now on new-op/new-rp
