### ISSUE TITLE
jwks read timed out

### ISSUE THREAD

**Issue by bitman694** [openid-certification/oidctest#166]
as it says, https://github.com/openid-certification/oidctest/issues/148
I try to test in OP-Basic mode, and something goes wrong. I can visit http://test.is.ac.cn/jwks and find public key.

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/oic-0.15.1-py3.6.egg/oic/utils/keyio.py", line 182, in do_remote
    r = requests.get(self.source, **args)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 520, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 630, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='test.is.ac.cn', port=80): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/otest-0.7.3-py3.6.egg/otest/aus/tool.py", line 87, in run_flow
    resp = _oper()
  File "/usr/local/lib/python3.6/dist-packages/otest-0.7.3-py3.6.egg/otest/operation.py", line 105, in __call__
    res = self.run(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/oidctest-0.7.5-py3.6.egg/oidctest/op/oper.py", line 216, in run
    res = self._run()
  File "/usr/local/lib/python3.6/dist-packages/oidctest-0.7.5-py3.6.egg/oidctest/op/oper.py", line 244, in _run
    request_args=self.req_args, **self.op_args)
  File "/usr/local/lib/python3.6/dist-packages/otest-0.7.3-py3.6.egg/otest/operation.py", line 171, in catch_exception_and_error
    res = func(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/oic-0.15.1-py3.6.egg/oic/oic/__init__.py", line 674, in do_access_token_request
    authn_method, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/oic-0.15.1-py3.6.egg/oic/oauth2/__init__.py", line 738, in do_access_token_request
    http_args=http_args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/oic-0.15.1-py3.6.egg/oic/oauth2/__init__.py", line 661, in request_and_return
    **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/oic-0.15.1-py3.6.egg/oic/oauth2/__init__.py", line 615, in parse_request_response
    state, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/oic-0.15.1-py3.6.egg/oic/oauth2/__init__.py", line 542, in parse_response
    verf = resp.verify(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/oic-0.15.1-py3.6.egg/oic/oic/message.py", line 339, in verify
    self["id_token"] = verify_id_token(self, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/oic-0.15.1-py3.6.egg/oic/oic/message.py", line 296, in verify_id_token
    idt = IdToken().from_jwt(_jws, **args)
  File "/usr/local/lib/python3.6/dist-packages/oic-0.15.1-py3.6.egg/oic/oauth2/message.py", line 662, in from_jwt
    _jw, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/oic-0.15.1-py3.6.egg/oic/oauth2/message.py", line 556, in get_verify_keys
    _key = keyjar.get_key_by_kid(_kid, _iss)
  File "/usr/local/lib/python3.6/dist-packages/oic-0.15.1-py3.6.egg/oic/utils/keyio.py", line 616, in get_key_by_kid
    _key = kb.get_key_with_kid(kid)
  File "/usr/local/lib/python3.6/dist-packages/oic-0.15.1-py3.6.egg/oic/utils/keyio.py", line 342, in get_key_with_kid
    self.update()
  File "/usr/local/lib/python3.6/dist-packages/oic-0.15.1-py3.6.egg/oic/utils/keyio.py", line 273, in update
    res = self.do_remote()
  File "/usr/local/lib/python3.6/dist-packages/oic-0.15.1-py3.6.egg/oic/utils/keyio.py", line 186, in do_remote
    REMOTE_FAILED.format(self.source, str(err)))
  File "/usr/local/lib/python3.6/dist-packages/oic-0.15.1-py3.6.egg/oic/utils/keyio.py", line 40, in raise_exception
    raise excep(_err, 'application/json')
oic.utils.keyio.UpdateFailed: {"error": "service_error", "error_description": "Remote key update from 'http://test.is.ac.cn/jwks' failed, HTTP status HTTPConnectionPool(host='test.is.ac.cn', port=80): Read timed out. (read timeout=5)"}

**Comment by zandbelt** [comment]
It seems you're running from a docker container that does not have access to that hostname/IP address.

**Comment by bitman694** [comment]
@zandbelt 
sorry for that. I temporarily closed that service yesterday and that's not the real reason. I'm going to keep it opening these days.
I can access that link with my browser:
        Request URL: http://test.is.ac.cn/jwks
        Request Method: GET
        Status Code: 200 OK
        Remote Address: 159.226.94.152:80
        Referrer Policy: no-referrer-when-downgrade
But I still get the error. And it appears sometimes(not all the time).
Do you think it's network connection problem that cause this error?

thanks
