### ISSUE TITLE
cannot delete OP test instance

### ISSUE THREAD

**Issue by zandbelt** [openid-certification/oidctest#3]
Deleting a registered instance from the OP test suite results in:

```
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/CherryPy-8.9.1-py3.6.egg/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/CherryPy-8.9.1-py3.6.egg/cherrypy/lib/encoding.py", line 220, in call
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/CherryPy-8.9.1-py3.6.egg/cherrypy/_cpdispatch.py", line 60, in call
    return self.callable(*self.args, **self.kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/oidctest-0.7.0-py3.6.egg/oidctest/tt/action.py", line 147, in index
    return self.delete(iss, tag, ev)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/oidctest-0.7.0-py3.6.egg/oidctest/tt/action.py", line 244, in delete
    _key = self.app.assigned_ports(*uqp)
TypeError: 'AssignedPorts' object is not callable
```

**Comment by rohe** [comment]
Fixed by https://github.com/rohe/oidctest/commit/40aad22da2a5f7d61016817fa31536379c9bfeec

**Comment by zandbelt** [comment]
The delete basically works but it appears that https://github.com/rohe/oidctest/commit/40aad22da2a5f7d61016817fa31536379c9bfeec#diff-df6251df6c7a492f91512806da0c3156R259 does not take into account whether my instance is running on https and it redirects to plain http which results in an SSL handshake error.

**Comment by rohe** [comment]
Ah, it took the URL from the configuration .. I think.
What's the definition of BASE in your tt_conf.py ?

**Comment by zandbelt** [comment]
`BASE = 'https://localhost'`

**Comment by rohe** [comment]
Sorry the config file that is interesting is config.py so what's BASE in that.

**Comment by zandbelt** [comment]
hmm, `BASE` is not defined, but `BASE_URL = 'http://localhost'`...

**Comment by rohe** [comment]
Right ! Should be https if that is what you're running.

**Comment by zandbelt** [comment]
confirmed!

**Comment by sjudson** [comment]
I continue to see issues with trying to delete an issuer through the UI.

![openid_failed_delete](https://cloud.githubusercontent.com/assets/20324824/25407609/f4a2c0f8-29d8-11e7-94a4-846e469f6a81.jpeg)

Although I do wonder if this has not yet been implemented, as I see no access control on deleting them as it were.

**Comment by zandbelt** [comment]
The log on the server shows:
```
2017-04-25 16:44:27,078 oidctest.tt.action:INFO ent:66.44.63.218, vpath: ['sjudson-auth0.auth0.com', 'default']
2017-04-25 16:44:27,079 oidctest.tt.action:INFO delete test tool configuration
2017-04-25 16:44:27,079 cherrypy.error.140433934311040:ERROR [25/Apr/2017:16:44:27] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/CherryPy-8.9.1-py3.5.egg/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python3.5/dist-packages/CherryPy-8.9.1-py3.5.egg/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/CherryPy-8.9.1-py3.5.egg/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.5/dist-packages/oidctest-0.7.0-py3.5.egg/oidctest/tt/action.py", line 206, in index
    return self.delete(iss, tag, ev)
  File "/usr/local/lib/python3.5/dist-packages/oidctest-0.7.0-py3.5.egg/oidctest/tt/action.py", line 265, in delete
    del self.app.assigned_ports[_key]
  File "/usr/local/lib/python3.5/dist-packages/oidctest-0.7.0-py3.5.egg/oidctest/ass_port.py", line 38, in __delitem__
    del self._db[key]
KeyError: 'sjudson-auth0.auth0.com][default'

```

Which suggests some key concatenation issue @rohe 

I believe as it stands there is no access control on any registration action.

**Comment by rohe** [comment]
None.
But nothing is thrown away.
If you delete a configuration it's backup'ed before it's removed.
I or Hans can restore a configuration if needed.
Dealing with access control is slightly problematic.

**Comment by zandbelt** [comment]
Yeah, I'd consider access control a different topic worth a separate (enhancement) ticket.

We still need to solve this issue: removing `sjudson-auth0.auth0.com/default` fails but removing my newly created instance works after the previous fix (just reconfirmed that).

**Comment by rohe** [comment]
It's gone now. I managed to remove it using the web interface. No manual command line script :-)

**Comment by zandbelt** [comment]
Right but I meant to solve the bug in the code, not the actual deletion of the instance. My guess is that re-registering and deleting would result in the same error again.

**Comment by rohe** [comment]
No it shouldn't. I think I fixed the bug.

**Comment by zandbelt** [comment]
Ok, then @sjudson can you confirm?

**Comment by zandbelt** [comment]
@sjudson can you confirm this works for you so we can close it?

**Comment by zandbelt** [comment]
My testing makes me believe this is fixed.
