### ISSUE TITLE
OP-prompt-login shouldn't depend on "auth_time"

### ISSUE THREAD

**Issue by zandbelt** [openid-certification/oidctest#36]
`OP-prompt-login` checks to see if two consecutive authentication flows result in two different `id_token`'s by checking the `auth_time` claim between them here:
https://github.com/openid-certification/oidctest/blob/master/src/oidctest/op/check.py#L1073

However, `auth_time` is not a required claim. It is only [required](http://openid.net/specs/openid-connect-core-1_0.html#IDToken) when `max_age` is requested or `auth_time` was a requested claim but adding those would make the test test something different.

Checking `iat`, `jti`, the signature, or other indicators that the tokens are different would be better, optionally depending on `auth_time` when it happens to be provided. Not failing when `auth_time` is not provided would at least be the right behavior.

**Comment by zandbelt** [comment]
It does appear that OPs may pass this test successfully when *no* auth_time was provided although (as reported by @panva and for MITREid) though I fail to see how the code allows for that case.

Even if so, the test should then probably be improved to detect that in fact two different tokens were produced, not originating from an existing SSO session, according to the suggestion(s) in the first comment.

**Comment by panva** [comment]
two different tokens do not mean two different auth events, jti, iat may be different for the same session and just a re-auth with prompt=none. auth_time is the only way to check authentication was performed

why not just provide max_age=xx to the second authentication which has the prompt? This is a way to force auth_time to present even for OPs without the support for claims parameter. Alternatively (for dynamic registration) default_max_age and/or require_auth_time.

**Comment by zandbelt** [comment]
I did not think it was required for the OP to support `max_age` but apparently it is:

> max_age
> OPTIONAL. Maximum Authentication Age. 
> [...]
> If the elapsed time is greater than this value, the OP MUST attempt to actively re-authenticate the End-User.
> [...]
> When max_age is used, the ID Token returned MUST include an auth_time Claim Value.

**Comment by zandbelt** [comment]
Anyway, there seems to be another issue with the code too: even when the server log complains about `auth_time` missing:
```
2017-07-07 18:21:23,235 oic.oauth2.message:DEBUG Key set summary for https://guarded-cliffs-8635.herokuapp.com: RSA:sig:r1LkbBo3925Rb2ZFFrKyU3MVex9T2817Kx0vbi6i_Kc, RSA:enc:w5kPRdJWODnYjihMgqs0tHkKk-e5OxU4DnSCZDkF_h0, EC::MFZeG102dQiqbANoaMlW_Jmf7fOZmtRsHt77JFhTpF0, EC::FQGs0SrPDKtD8skxqMQZ060XPBbXyrs05qKTLH9MUqY, EC::2QLqShv6DZYE-X44cpZ1bmgDO1XqsOBCyidpR4qt6W8
2017-07-07 18:21:23,235 oic.utils.keyio:DEBUG Issuer '2e3a5bd8-a712-44b9-8e9c-6977abc7de2f' not found, available key issuers: ['', 'https://guarded-cliffs-8635.herokuapp.com']
2017-07-07 18:21:23,235 oic.oauth2.message:DEBUG Key set summary for 2e3a5bd8-a712-44b9-8e9c-6977abc7de2f:
2017-07-07 18:21:23,235 oic.oauth2.message:DEBUG Found signing key.
2017-07-07 18:21:23,235 jwkest.jws:DEBUG Picking key by key type=RSA
2017-07-07 18:21:23,235 jwkest.jws:DEBUG Picking key based on alg=RS256, kid=r1LkbBo3925Rb2ZFFrKyU3MVex9T2817Kx0vbi6i_Kc and use=
2017-07-07 18:21:23,235 jwkest.jws:DEBUG Picked: kid:G91Zi19W7Lwa0rGu570gwP_rWfJTBUaWsghWEVEvdVs, use:sig, kty:RSA
2017-07-07 18:21:23,235 jwkest.jws:DEBUG Picked: kid:r1LkbBo3925Rb2ZFFrKyU3MVex9T2817Kx0vbi6i_Kc, use:sig, kty:RSA
2017-07-07 18:21:23,236 jwkest.jws:DEBUG Verified message using key with kid=r1LkbBo3925Rb2ZFFrKyU3MVex9T2817Kx0vbi6i_Kc
2017-07-07 18:21:23,237 otest.aus.tool:INFO <--<-- 8 --- Done -->-->
2017-07-07 18:21:23,237 otest.verify:DEBUG do_check(multiple-sign-on, {})
2017-07-07 18:21:23,239 otest.verify:ERROR [do_check] ExcList: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/otest-0.7.1-py3.5.egg/otest/verify.py", line 70, in do_check
    stat = chk(self.conv)
  File "/usr/local/lib/python3.5/dist-packages/otest-0.7.1-py3.5.egg/otest/check.py", line 121, in call
    _stat = self._func(conv)
  File "/usr/local/lib/python3.5/dist-packages/oidctest-0.7.0-py3.5.egg/oidctest/op/check.py", line 1073, in _func
    assert idt[0]["auth_time"] != idt[1]["auth_time"]
  File "/usr/local/lib/python3.5/dist-packages/oic-0.10.0.0-py3.5.egg/oic/oauth2/message.py", line 731, in getitem
    return self._dict[item]
KeyError: 'auth_time'

2017-07-07 18:21:23,239 otest.verify:ERROR [do_check] Exception: 'auth_time'
```
apparently the UI does not display this error and the test just passes.

**Comment by jricher** [comment]
If anything, having a missing or bad auth_time value shouldn't fail the test, but provide a warning. As stated above, these are hints to the RP about what happened.

**Comment by selfissued** [comment]
We can continue comparing auth_time if it exists and let it pass if it doesn't.  We already require the screen shot, so we have another means of verifying that a new authentication occurred.

**Comment by selfissued** [comment]
We want the test suite not to throw an exception in this case.  A code change is needed for that.

**Comment by zandbelt** [comment]
@rohe: the proposed patch is this:
```
diff --git a/src/oidctest/op/check.py b/src/oidctest/op/check.py
index d9be2a2..25ed0b4 100644
--- a/src/oidctest/op/check.py
+++ b/src/oidctest/op/check.py
@@ -1071,6 +1071,9 @@
         # verify that it is in fact two separate authentications
         try:
             assert idt[0]["auth_time"] != idt[1]["auth_time"]
+        except KeyError:
+            self._message = "No \"auth_time\" found in both ID tokens so it cannot be compared"
+            self._status = WARNING            
         except AssertionError:
             self._message = "Not two separate authentications!"
             try:

```

**Comment by rohe** [comment]
Should work

**Comment by zandbelt** [comment]
I left out the `self._status = WARNING ` for now since the test can be totally fine even if no `auth_time` is presented. For now just the stacktrace in the server log is gone, the other code is as was before.

**Comment by panva** [comment]
I'm fine with issuing a warning so long as the test suite attempts to request auth_time from a server, this can be done by all the following means at once

- (easiest solution) for dynamic clients is to register with require_auth_time: true
- max_age for both requests (albeit with some ridiculous values)
- claims parameter requesting that id_token returns auth_time (either essential or voluntary)

Issuing a warning when the test suite does not require the claim to be returned will only confuse more testers.
