### ISSUE TITLE
OP-Token-refresh expects an id_token

### ISSUE THREAD

**Issue by zandbelt** [openid-certification/oidctest#5]
As far as I know there's no obligation - and in fact it does not make sense - to return an id_token in a refresh_token flow. It seems the OP test suite expects one and fails if there isn't one returned from the token endpoint:
```
2017-04-21 14:51:31,345 otest.aus.tool:ERROR [RefreshToken] ExcList: Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/otest-0.7.0-py3.6.egg/otest/aus/tool.py", line 86, in run_flow
    resp = _oper()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/otest-0.7.0-py3.6.egg/otest/operation.py", line 103, in __call__
    res = self.run(*args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/oidctest-0.7.0-py3.6.egg/oidctest/op/oper.py", line 266, in run
    self.catch_exception_and_error(self._run)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/otest-0.7.0-py3.6.egg/otest/operation.py", line 151, in catch_exception_and_error
    res = func(**kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/oidctest-0.7.0-py3.6.egg/oidctest/op/oper.py", line 307, in _run
    if not same_issuer(self.conv.info["issuer"], atr["id_token"]["iss"]):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/oic-0.10.0.0-py3.6.egg/oic/oauth2/message.py", line 730, in __getitem__
    return self._dict[item]
KeyError: 'id_token'

```

The culprit seems to be in:
https://github.com/openid-certification/oidctest/blob/master/src/oidctest/op/oper.py#L307

The test output:
```
33.528	http response	
url:https://<host>/as/token.oauth2 status_code:200
33.528	response	{'access_token': 'ocNeja7rkhDuPz69WhffzmKJ0Xyp', 'refresh_token': '9UhEJSleDbnMFXXHZlV1OwoXuxjaHUw2VJiB6tuJXH', 'token_type': 'Bearer', 'expires_in': 7200}
33.529	AccessTokenResponse	
{
    "access_token": "ocNeja7rkhDuPz69WhffzmKJ0Xyp",
    "expires_in": 7200,
    "refresh_token": "9UhEJSleDbnMFXXHZlV1OwoXuxjaHUw2VJiB6tuJXH",
    "token_type": "Bearer"
}
33.529	exception	
KeyError:'id_token'
33.529	condition	RefreshToken:OP-Token-refresh: status=ERROR, message='id_token'
```

**Comment by rohe** [comment]
Removed the issuer check since it was dependent on there being an IdToken in the response from the token endpoint.

**Comment by zandbelt** [comment]
Will check https://github.com/rohe/oidctest/commit/919ea42efc059ed245222731b0320157b38ea40f asap. and confirm!

**Comment by zandbelt** [comment]
interestingly enough it solved it partly but there's another related issue left:

```
2017-04-25 21:47:05,492 oic.oauth2:DEBUG Verify response with {'keyjar': <KeyJar(issuers=['', 'https://zmartzone.eu'])>, 'client_id': 'localhost-certification', 'iss': 'https://zmartzone.eu'}
2017-04-25 21:47:05,495 otest.aus.tool:ERROR [RefreshToken] ExcList: Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/otest-0.7.0-py3.6.egg/otest/aus/tool.py", line 86, in run_flow
    resp = _oper()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/otest-0.7.0-py3.6.egg/otest/operation.py", line 103, in __call__
    res = self.run(*args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/oidctest-0.7.0-py3.6.egg/oidctest/op/oper.py", line 266, in run
    self.catch_exception_and_error(self._run)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/otest-0.7.0-py3.6.egg/otest/operation.py", line 151, in catch_exception_and_error
    res = func(**kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/oidctest-0.7.0-py3.6.egg/oidctest/op/oper.py", line 307, in _run
    return atr
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/oic-0.10.0.0-py3.6.egg/oic/oauth2/message.py", line 730, in __getitem__
    return self._dict[item]
KeyError: 'id_token'

2017-04-25 21:47:05,495 otest.aus.tool:ERROR [RefreshToken] Exception: 'id_token'
```

why there's a dict key error on a return statement is beyond my current Python knowledge...

**Comment by rohe** [comment]
That's plain weird.
Your running 3.6, hmm ?
I'll see if I can replicate this.

**Comment by zandbelt** [comment]
Yeah, I double-check that the code is really updated to include your latest changes.

**Comment by rohe** [comment]
Can't replicate the problem on my machine.

**Comment by zandbelt** [comment]
And I cannot either... the only thing that I did in the mean time is run `python setup.py install` again, which should be superfluous... Closing it now because if there's any issue I guess it is related to some cache or file system thing, not the actual code.

**Comment by rohe** [comment]
Sounds reasonable
