### ISSUE TITLE
Internal Error attempting to display test status

### ISSUE THREAD

**Issue by KimRasmussen** [openid-certification/oidctest#55]
Hi,

At https://op.certification.openid.net:60345/test_info/OP-ClientAuth-SecretPost-Static I am getting an internal error when attempting to display the status of a test.

Hans looked at the server logs, and got this snippet:

>2017-10-01 17:00:16,603 jwkest.jws:DEBUG Picked: kid:k1, use:sig, kty:RSA
>2017-10-01 17:00:16,604 jwkest.jws:DEBUG Verified message using key with kid=k1
>2017-10-01 17:00:16,604 otest.aus.tool:INFO <--<-- 4 --- Done -->-->
>2017-10-01 17:00:16,604 otest.verify:DEBUG do_check(verify-response, {'response_cls': ['AuthorizationResponse', 'AccessTokenResponse']})
2017-10-01 17:00:16,607 cherrypy.error.139634396597440:ERROR [01/Oct/2017:17:00:16] HTTP
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/oidctest-0.7.0-py3.5.egg/oidctest/optt/__init__.py", line 171, in authz_cb
    response=kwargs)
  File "/usr/local/lib/python3.5/dist-packages/otest-0.7.1-py3.5.egg/otest/aus/tool.py", line 230, in async_response
    return self.run_flow(self.sh["testid"], index=index)
  File "/usr/local/lib/python3.5/dist-packages/otest-0.7.1-py3.5.egg/otest/aus/tool.py", line 122, in run_flow
    tinfo = self.store_result(res)
  File "/usr/local/lib/python3.5/dist-packages/otest-0.7.1-py3.5.egg/otest/tool.py", line 113, in store_result
    res.write_info(tinfo)
  File "/usr/local/lib/python3.5/dist-packages/otest-0.7.1-py3.5.egg/otest/result.py", line 138, in write_info
    output.extend(trace_output(_events))
  File "/usr/local/lib/python3.5/dist-packages/otest-0.7.1-py3.5.egg/otest/summation.py", line 121, in trace_output
    element.append(layout(start, event))
  File "/usr/local/lib/python3.5/dist-packages/otest-0.7.1-py3.5.egg/otest/events.py", line 369, in layout
    elem.extend(TO_STR[event.typ](event))
  File "/usr/local/lib/python3.5/dist-packages/otest-0.7.1-py3.5.egg/otest/events.py", line 347, in message_to_str
    json.dumps(event.data.to_dict(), sort_keys=True, indent=4,
  File "/usr/local/lib/python3.5/dist-packages/oic-0.10.0.0-py3.5.egg/oic/oauth2/message.py", line 321, in to_dict
    _res[key] = val.to_dict(lev + 1)
  File "/usr/local/lib/python3.5/dist-packages/oic-0.10.0.0-py3.5.egg/oic/oauth2/message.py", line 322, in to_dict
    elif isinstance(val, list) and isinstance(val[0], Message):
IndexError: list index out of range

I assume it is something in one of the response I sent back that it has trouble displaying, but I am not sure what is wrong.

It might very well be my response that for some reason is not valid, but I cannot see what is wrong with it.
I would appreciate any help you can provide...
Thanks.
/Kim

**Comment by KimRasmussen** [comment]
The original one I linked to, at port 60345 is working now and I managed to complete the basic testing.
So, just to test my luck, I created another one for testing implicit flow and it now fails with error 500 without having run a single test.

https://op.certification.openid.net:60956/OP-Response-Missing

**Comment by zandbelt** [comment]
Wrt. that last error: just make sure that you've configured the mandatory "client_id" and "client_secret" on this page: https://op.certification.openid.net:60000/action/https%3A%2F%2Ftest.portalprotect.dk%2F/implicit?action=configure

Input checking, logging and error messaging should be improved for this.

**Comment by KimRasmussen** [comment]
Argh, sorry - my mistake. Thanks for the pointer.
