### ISSUE TITLE
claims partial results, used to be green

### ISSUE THREAD

**Issue by panva** [openid-certification/oidctest#6]
Not sure what's changed,

  1)  OP-claims-Combined:
     Error: expected status to be Green, but got "Yellow"
  2)  OP-claims-IDToken:
     Error: expected status to be Green, but got "Yellow"
  3)  OP-claims-Split:
     Error: expected status to be Green, but got "Yellow"
  4)  OP-claims-acr-essential:
     Error: expected status to be Green, but got "Yellow"
  5)  OP-claims-auth_time-essential:
     Error: expected status to be Green, but got "Yellow"
  6)  OP-claims-essential:
     Error: expected status to be Green, but got "Yellow"
  7)  OP-claims-essential+voluntary:
     Error: expected status to be Green, but got "Yellow"

Got these across all profiles just a few minutes ago. (oh and my test instance port changed to [60011](https://new-op.certification.openid.net:60011/display#claims))

**Comment by zandbelt** [comment]
A lot of this type of logs on the server side:
```
Message: '91.52.24.97 - - [24/Apr/2017:13:37:58] "GET /OP-claims-essential+voluntary HTTP/1.1" 303 838 "https://new-op.certification.openid.net:60011/display" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.5/logging/__init__.py", line 984, in emit
    self.flush()
  File "/usr/lib/python3.5/logging/__init__.py", line 964, in flush
    self.stream.flush()
OSError: [Errno 5] Input/output error
Call stack:
  File "/usr/lib/python3.5/threading.py", line 882, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.5/dist-packages/CherryPy-8.9.1-py3.5.egg/cherrypy/wsgiserver/__init__.py", line 1594, in run
    conn.communicate()
  File "/usr/local/lib/python3.5/dist-packages/CherryPy-8.9.1-py3.5.egg/cherrypy/wsgiserver/__init__.py", line 1408, in communicate
    req.respond()
  File "/usr/local/lib/python3.5/dist-packages/CherryPy-8.9.1-py3.5.egg/cherrypy/wsgiserver/__init__.py", line 862, in respond
    self.server.gateway(self).respond()
  File "/usr/local/lib/python3.5/dist-packages/CherryPy-8.9.1-py3.5.egg/cherrypy/wsgiserver/__init__.py", line 2335, in respond
    response = self.req.server.wsgi_app(self.env, self.start_response)
  File "/usr/local/lib/python3.5/dist-packages/CherryPy-8.9.1-py3.5.egg/cherrypy/_cptree.py", line 287, in __call__
    return app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/CherryPy-8.9.1-py3.5.egg/cherrypy/_cptree.py", line 153, in __call__
    return self.wsgiapp(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/CherryPy-8.9.1-py3.5.egg/cherrypy/_cpwsgi.py", line 450, in __call__
    return head(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/CherryPy-8.9.1-py3.5.egg/cherrypy/_cpwsgi.py", line 153, in __call__
    self.throws
  File "/usr/local/lib/python3.5/dist-packages/CherryPy-8.9.1-py3.5.egg/cherrypy/_cpwsgi.py", line 168, in __init__
    self.nextapp, self.environ, self.start_response,
  File "/usr/local/lib/python3.5/dist-packages/CherryPy-8.9.1-py3.5.egg/cherrypy/_cpwsgi.py", line 189, in trap
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/CherryPy-8.9.1-py3.5.egg/cherrypy/_cpwsgi.py", line 105, in __call__
    return self.nextapp(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/CherryPy-8.9.1-py3.5.egg/cherrypy/_cpwsgi.py", line 438, in tail
    return self.response_class(environ, start_response, self.cpapp)
  File "/usr/local/lib/python3.5/dist-packages/CherryPy-8.9.1-py3.5.egg/cherrypy/_cpwsgi.py", line 244, in __init__
    self.run()
  File "/usr/local/lib/python3.5/dist-packages/CherryPy-8.9.1-py3.5.egg/cherrypy/_cpwsgi.py", line 347, in run
    request.run(meth, path, qs, rproto, headers, rfile)
  File "/usr/local/lib/python3.5/dist-packages/CherryPy-8.9.1-py3.5.egg/cherrypy/_cprequest.py", line 612, in run
    cherrypy.log.access()
  File "/usr/local/lib/python3.5/dist-packages/CherryPy-8.9.1-py3.5.egg/cherrypy/__init__.py", line 337, in access
    return request.app.log.access()
  File "/usr/local/lib/python3.5/dist-packages/CherryPy-8.9.1-py3.5.egg/cherrypy/_cplogging.py", line 285, in access
    logging.INFO, self.access_log_format.format(**atoms))
```
It looks like the logfile was being rolled over at the same time.
Could you try again, perhaps by restarting the test instance?

**Comment by panva** [comment]
I got these results consistently across all profile runs, before each profile run a reconfiguration happens, isn't a restart part of this process?

I've triggered a re-run anyway > https://travis-ci.org/panva/oidc-provider-conformance-tests/builds/225295830

**Comment by panva** [comment]
No joy, still yellow on the same 7

**Comment by zandbelt** [comment]
yeah, you're right about the restart in your conformance test case

the error is still the same: seems like it has problems writing the access log; I'm handing over to Roland...

**Comment by rohe** [comment]
I don't think the log errors has anything to do with what Filip is seen. But ...
I've tried to replicate Filip's problem on my machine and has failed so far.
So, there is something I haven't figured out yet.
I've added a couple of log lines to hopefully get some clue.

**Comment by rohe** [comment]
The problems with the tests are fixed. It was a bug in the underlying pyoidc library.
Temporary fix applied on the Symantec machine until I can get the library fixed.

**Comment by rohe** [comment]
Permanent fix. Uses my own properly working function instead of the changed (broken?) of pyoidc.

**Comment by panva** [comment]
confirmed https://travis-ci.org/panva/oidc-provider-conformance-tests/builds/225689204
feel free to close once permanently fixed in pyoidc

**Comment by zandbelt** [comment]
Closing this as the fix is permanent, overriding pyoidc in oidctest.
