### ISSUE TITLE
improve error message when at_hash is missing

### ISSUE THREAD

**Issue by zandbelt** [openid-certification/oidctest#95]
When the `at_hash` property is missing in flows where it is required (e.g. `id_token token`, currently there's no user facing error message at all. The tool just returns to the main page with no logs or messages. The server log is like pasted below:
```
2018-05-22 07:11:06,170 root:DEBUG KeyBundle fetch keys from: https://city-of-london-police.i2eweb.com:3000/hello/jwks.json
2018-05-22 07:11:06,171 requests.packages.urllib3.connectionpool:INFO Starting new HTTPS connection (1): city-of-london-police.i2eweb.com
2018-05-22 07:11:06,492 requests.packages.urllib3.connectionpool:DEBUG "GET /hello/jwks.json HTTP/1.1" 200 1366
2018-05-22 07:11:06,494 oic.utils.keyio:WARNING Wrong Content_type
2018-05-22 07:11:06,494 oic.utils.keyio:DEBUG Loaded JWKS: {"keys":[{"kty":"RSA","kid":"28sa_FzPdJ9Puvvi_FAielDPlNWpSH4rpGlENJD7AcI","use":"sig","alg":"RS256","e":"AQAB","n":"qhBDrSoiu6aA8NV5JZb35hqR6N1aLlYvtOjh_94LEgNo6_hjQq1xyCihvqrOWpKkPX_T9y6DXTKm2zCTXXT7qHZerqDj937G2vlEH0xnl_6N5ziemCdDAH3k39Wcfbv-Z1_FD7348xSv6Wx_UuZtlnNz5phvP7xdO-2Jqnry50G4ZZIWJoozJ-_VfTdfGhIu50XqBCcCiq4Xs9tGkjO-lqskJVcqdOW0bjGr3eis-ZBEko89LN0i0h7vI5pCV7qkh2PCrOI_CKZ-sXCIViUpwkoov35ntjcLwDkebTR0J45xEG4FK5pvX-Xg0PpE-lkex7Cx_d30W1EOra42Px3RsQ"},{"kty":"RSA","kid":"5wAIiXiJkPLdsGe1ZZiTleUsktUyUHSw5ZQnYbEE5rs","use":"sig","alg":"RS256","e":"AQAB","n":"kPMjJtRbnC1ebEFx3brsfRobuzJES1CZhGS8A9vAo7EVYXt775bKF2PLbZIXjLX3miuQO4o5eowNKpzlemTqiVcA-fCH7QVke8sD1HaoA2dVkhz3xxF8lINUET9oHOMz8CcXwsyt8ErePLm5lmqAlgNyZHLF6dBGe2BO2dANyhfRnyParMSC_GNDKqZGcn0GL7TIGojWKPaWGddo8E09TWshJhBPcVu0Fj41d3K05gJnvlVOQaH1Rw-OQlb-TrZFAGoHXs1MkqMIHr2dXYNfRwmMsuZTU7b03GopAIhdf7wxz3KXoKSnOuq7E4vXt1ZsgPEQWyWTopCQJNxU_erADw"},{"kty":"RSA","kid":"gMMVEwt8DCjAddaHkyMBAxbpvdpaGWMY5w5HhHfvsgA","use":"sig","alg":"RS256","e":"AQAB","n":"g-Msok5Jrkwz7JPy4u7ke1mESxBOUH8Aygr9eYMrkaUQ34Vuspn2nWb9SgTnU36boAkYlqbEv3pDcWnFvmXvbY5S0qXtcycERERmMf6o4q1JOS0yXID0u0-UUftTURONhAjXsmqRK9vxY6XbjDbHnAFmBF0V_kaYuYI-i7XTrf6AEYUnWYTi_QXgqInGp2lshUv52v3wH6OUiFwxc83Auf-Hfsmuyfb-jMKHkKECUitaszATiw78dGXY7EimHqTzDGYf34fgGRK_iJV2pGj1luh3QOsYVNg8z2JMDf9cUvB-SF4zSvRy60FIiR97Klv-69D67GtGrqItVxz8qWTUHQ"}]} from https://city-of-london-police.i2eweb.com:3000/hello/jwks.json
2018-05-22 07:11:06,494 oic.utils.keyio:DEBUG Loaded JWKS: {"keys":[{"kty":"RSA","kid":"28sa_FzPdJ9Puvvi_FAielDPlNWpSH4rpGlENJD7AcI","use":"sig","alg":"RS256","e":"AQAB","n":"qhBDrSoiu6aA8NV5JZb35hqR6N1aLlYvtOjh_94LEgNo6_hjQq1xyCihvqrOWpKkPX_T9y6DXTKm2zCTXXT7qHZerqDj937G2vlEH0xnl_6N5ziemCdDAH3k39Wcfbv-Z1_FD7348xSv6Wx_UuZtlnNz5phvP7xdO-2Jqnry50G4ZZIWJoozJ-_VfTdfGhIu50XqBCcCiq4Xs9tGkjO-lqskJVcqdOW0bjGr3eis-ZBEko89LN0i0h7vI5pCV7qkh2PCrOI_CKZ-sXCIViUpwkoov35ntjcLwDkebTR0J45xEG4FK5pvX-Xg0PpE-lkex7Cx_d30W1EOra42Px3RsQ"},{"kty":"RSA","kid":"5wAIiXiJkPLdsGe1ZZiTleUsktUyUHSw5ZQnYbEE5rs","use":"sig","alg":"RS256","e":"AQAB","n":"kPMjJtRbnC1ebEFx3brsfRobuzJES1CZhGS8A9vAo7EVYXt775bKF2PLbZIXjLX3miuQO4o5eowNKpzlemTqiVcA-fCH7QVke8sD1HaoA2dVkhz3xxF8lINUET9oHOMz8CcXwsyt8ErePLm5lmqAlgNyZHLF6dBGe2BO2dANyhfRnyParMSC_GNDKqZGcn0GL7TIGojWKPaWGddo8E09TWshJhBPcVu0Fj41d3K05gJnvlVOQaH1Rw-OQlb-TrZFAGoHXs1MkqMIHr2dXYNfRwmMsuZTU7b03GopAIhdf7wxz3KXoKSnOuq7E4vXt1ZsgPEQWyWTopCQJNxU_erADw"},{"kty":"RSA","kid":"gMMVEwt8DCjAddaHkyMBAxbpvdpaGWMY5w5HhHfvsgA","use":"sig","alg":"RS256","e":"AQAB","n":"g-Msok5Jrkwz7JPy4u7ke1mESxBOUH8Aygr9eYMrkaUQ34Vuspn2nWb9SgTnU36boAkYlqbEv3pDcWnFvmXvbY5S0qXtcycERERmMf6o4q1JOS0yXID0u0-UUftTURONhAjXsmqRK9vxY6XbjDbHnAFmBF0V_kaYuYI-i7XTrf6AEYUnWYTi_QXgqInGp2lshUv52v3wH6OUiFwxc83Auf-Hfsmuyfb-jMKHkKECUitaszATiw78dGXY7EimHqTzDGYf34fgGRK_iJV2pGj1luh3QOsYVNg8z2JMDf9cUvB-SF4zSvRy60FIiR97Klv-69D67GtGrqItVxz8qWTUHQ"}]} from https://city-of-london-police.i2eweb.com:3000/hello/jwks.json
2018-05-22 07:11:06,495 oic.oauth2.message:DEBUG Found signing key.
2018-05-22 07:11:06,495 jwkest.jws:DEBUG Picking key by key type=RSA
2018-05-22 07:11:06,495 jwkest.jws:DEBUG Picking key based on alg=RS256, kid=gMMVEwt8DCjAddaHkyMBAxbpvdpaGWMY5w5HhHfvsgA and use=
2018-05-22 07:11:06,496 jwkest.jws:DEBUG Picked: kid:wt25OgyR_nzG3OoQ7daa2rL6-gMnFdfRzBjhUVPu8RQ, use:sig, kty:RSA
2018-05-22 07:11:06,496 jwkest.jws:DEBUG Picked: kid:gMMVEwt8DCjAddaHkyMBAxbpvdpaGWMY5w5HhHfvsgA, use:sig, kty:RSA
2018-05-22 07:11:06,496 jwkest.jws:DEBUG Verified message using key with kid=gMMVEwt8DCjAddaHkyMBAxbpvdpaGWMY5w5HhHfvsgA
2018-05-22 07:11:06,497 otest.handling:ERROR [run_sequence] ExcList: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/otest-0.7.4-py3.5.egg/otest/aus/request.py", line 327, in parse_response
    keyjar=_conv.entity.keyjar  # , algs=algs
  File "/usr/local/lib/python3.5/dist-packages/oic-0.14.0-py3.5.egg/oic/oauth2/__init__.py", line 562, in parse_response
    verf = resp.verify(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/oic-0.14.0-py3.5.egg/oic/oic/message.py", line 358, in verify
    raise MissingRequiredAttribute("Missing at_hash property", idt)
oic.oauth2.message.MissingRequiredAttribute: Missing required attribute 'Missing at_hash property'

2018-05-22 07:11:06,497 otest.handling:ERROR [run_sequence] Exception: Missing required attribute 'Missing at_hash property'
```
We should generate a user facing error message for this (and similar cases) just like done for #65

**Comment by zandbelt** [comment]
deployed as part of OP version 2.1.2
