### ISSUE TITLE
OP-Req-id_token_hint: show user facing error message when the OP returns an error

### ISSUE THREAD

**Issue by zandbelt** [openid-certification/oidctest#96]
When the OP returns an error in the `OP-Req-id_token_hint` (though this is probably the case for more tests), the test tool only logs a stacktrace in the server side log but there's no user facing error message, the tool just returns to the test list with no message/trace. There should be a user facing error message in the HTML GUI.

```
2018-05-23 08:04:04,631 otest.aus.tool:INFO <=<=<=<=< OP-Req-id_token_hint >=>=>=>=>
2018-05-23 08:04:04,631 otest.aus.tool:INFO <--<-- 4 --- AccessToken -->-->
2018-05-23 08:04:04,632 otest.aus.tool:INFO <--<-- 5 --- AsyncAuthn -->-->
2018-05-23 08:04:04,633 cherrypy.access.140092469291720:INFO 212.198.197.64 - - [23/May/2018:08:04:04] "POST /authz_post HTTP/1.1" 303 2110 "https://op.certification.openid.net:61263/authz_cb" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134"
2018-05-23 08:04:05,592 cherrypy.access.140092469291720:INFO 212.198.197.64 - - [23/May/2018:08:04:05] "GET /authz_cb HTTP/1.1" 200 546 "https://op.certification.openid.net:61263/authz_cb" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134"
2018-05-23 08:04:05,727 otest.aus.tool:INFO <--<-- 5 --- <class 'oidctest.op.oper.AsyncAuthn'>
2018-05-23 08:04:05,728 otest.aus.request:INFO Response: error=invalid_request&error_description=The%20request%20is%20missing%20a%20required%20parameter%2C%20includes%20an%20invalid%20parameter%20value%2C%20includes%20a%20parameter%20more%20than%20once%2C%20or%20is%20otherwise%20malformed.%3A%20Error%3A%20no%20key%20found&state=55lqUysYFo5vCbkc
2018-05-23 08:04:05,728 oic.oauth2:DEBUG Initial response parsing => "{'error': 'invalid_request', 'state': '55lqUysYFo5vCbkc', 'error_description': 'The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.: Error: no key found'}"
2018-05-23 08:04:05,728 otest.aus.request:INFO Parsed response: {'error': 'invalid_request', 'state': '55lqUysYFo5vCbkc', 'error_description': 'The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.: Error: no key found'}
2018-05-23 08:04:05,728 otest.handling:ERROR [authz_cb] ExcList: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/oidctest-0.7.0-py3.5.egg/oidctest/optt/__init__.py", line 195, in authz_post
    response=kwargs)
  File "/usr/local/lib/python3.5/dist-packages/otest-0.7.4-py3.5.egg/otest/aus/tool.py", line 224, in async_response
    response=response)
  File "/usr/local/lib/python3.5/dist-packages/otest-0.7.4-py3.5.egg/otest/aus/request.py", line 347, in parse_response
    raise Break("Unexpected error response")
otest.Break: Unexpected error response
```

**Comment by rohe** [comment]
Added a general user facing error message.
Simplest possible, just dumping the stack trace.

There is a version 0.7.2 of oidctest on https://github.com/rohe/oidctest.
Note that it needs >= 0.7.1 of https://github.com/rohe/otest

**Comment by zandbelt** [comment]
deployed as part of OP version 2.1.2 now
